### PR TITLE
Not yet ready for Google

### LINKED ISSUE #1: Ital axis
Hi
Right now GF is not supporting the slant axis. In order to make an italic appear, we need it separated from the Roman (ie. 2 sources, 2 VF). But it means you won't have an axis to make to slope vary.

If you want this slant variation, then you need to call it slant (slnt) and follow the open-type spec in that regard (negative value). The downside is that you won't have a proper style-linked italic. Since we haven't stated on a fallback name (oblique, LeftLeaning…), there is a chance that the font doesn't get onboarded until further decision.

Cf this issue where we are still trying to figure out a solution for a slant axis: https://github.com/googlefonts/gftools/issues/295#issuecomment-824744342

What do you prefer?

### PR DESCRIPTION
**Pull request by RosaWagner**
fixes #1

### CODE REVIEW

**Comment by RosaWagner** [comment]
Hi, 
I edited the sources so there are as expected. Although there is few issues:

1. Your interpolation pace is linear, which may be wrong for a weight axis. You can review the location of the different instances in order to adjust the pace of the interpolation. You can read this article for more info: https://glyphsapp.com/learn/creating-a-variable-font (section "Axis Mapping at the end). The article show wrong values, just choose the coordinates of the instances and I will take care of setting up the axis mapping and AVAR table.

2. There is too much stem thickness values. this doesn't impact fonts generated for Google, it is more a general advice for good PS autohinting with Glyphs.

3. We can't apply monospace metadata correctly cause your font has some double glyphs width (ligatures and IJ). If we set up the parameter "is fixed pitch" as it should be for monospace font, it will force to apply the same width everywhere. This is as you wish since it is design decision, but IJ and ligatures are conventionally stand in a single glyph width. If you wish to keep the ligature style but in 2 width*1, you can use contextual alternates which replace the f by another with a longer bar.

4. You can name standard ligatures .liga, and discretionary ligatures .dlig to avoid manual opentype feature settings (which often leads to mistakes)

5. Few glyphs doesn't respect width*1, *0 or *2 convention. You can use this script to find them: https://github.com/mekkablue/Glyphs-Scripts/blob/master/Spacing/Monospace%20Checker.py Monospace width could easier be enforced if you remove the asynchronous metrics keys. With this script for example: https://github.com/mekkablue/Glyphs-Scripts/blob/master/Spacing/Remove%20Metrics%20Keys.py

**Comment by RosaWagner** [comment]
@displaay have you seen this pull request?

**Comment by displaay** [comment]
We are in the middle of discussion what is requested and what is matter of taste ;)
Thank you Rosalie, we will come back asap.

Martin

**Comment by RosaWagner** [comment]
@displaay 

I asked my colleague to clarify why is_fixed_pitch is needed when width * 0 and width * 2 is completely normal in a monospaced font. I got the answer that this parameter is important for fonts targeting specifically the Terminal and any developper app (which have a stricter policy for displaying monospaced fonts). I got some kind of an "authorization" to ignore this if you decide that you are not targeting the dev audience.

To keep in mind in your discussions:
About the matter of taste, GF is serving fonts to billions of websites, seen by users in many different environments, through a complicated API. Fonts have to match the specifications because otherwise they can break websites, or come in conflict with API automations and never be published. This is a matter of compromise for better accessibility. Finally, once the font is published, you can update it, but not if it contains any regression (difference of weight, line height, and spacing) even if the font looks better this way. Indeed, these regressions impact directly websites already using the font. This is to encourage you to have extra care for the 3 points mentioned: distribution of weight through the family, vertical metrics, and horizontal spacing.

**Comment by displaay** [comment]
Hi Rosa,
so we've just updated the sources. Now:
- dlig, liga are named corespondingly
- stem widths are consistent
- all glyphs are either 0*, 1*, 2* or 3* width

We decided not to change the axis mapping.

Also we would like to keep these wider glyphs, if the algorithms won't penalize the font or even worse throw the font out of the monospaced category. Let us know what to improve further. Thx for your time!

**Pull request merged**
