### PR TITLE
Regenerated fonts 1.002

### PR DESCRIPTION
**Pull request by RosaWagner**
@displaay I re-built the fonts and gonna ship the fonts just after that.

- Authors and Manufacturer will be credited in GF speciment page. You can help us fill up your profile by filling this form (Martin Vácha, Displaay, so 2 times):
https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

- You can send me promotional material for twitter if you want to be promoted when the font will be published. For we need:
1-3 pics (usually 4:3 but any twitter-friendly size will do) + people to tag. I'll deal with the text since we have some kind of a template. You can get inspired by already posted stuff: https://twitter.com/googlefonts/status/1379432704362483715

- You can add to your readme this kind of instruction to build the font:

## Building the font
Please install gftools in a virtual environment:
1. go to the root of your local clone of this repository: `cd path/to/dir`
2. there, create a venv: `python3 -m venv env`
3. Activate the venv: `source env/bin/activate`
4. Install gftools: `pip install gftools`

Before building the font, go to the sources directory of your local clone. Make sure you activated the virtual env. From there you can run: `gftools builder config.yaml`

### CODE REVIEW

**Comment by displaay** [comment]
Hi Rosalie,

Thank you.
I have filled the form.
Here <https://www.dropbox.com/sh/m4seitzvmcg37z5/AABQ0kke4yDHmcyfD7o4XlzTa?dl=0> is promotional material.
and Jan is going to build the fonts

Best regards, 

Martin Vácha
+420 608 450 545

**Comment by RosaWagner** [comment]
Thanks.
Can you indicate your 4 favourite images?

**Comment by displaay** [comment]
Yellow labeled ;)
M

**Comment by RosaWagner** [comment]
@displaay So… are you going to merge the pull request? I can't ship the fonts if they are not in the repo, and I go in holidays next week.

**Pull request merged**
